/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/*
    아이템 보여주고 1번째는 아이템 번호, 2번째는 아이템 이름 
*/
package frame;

import database.ProductDAO;
import database.ProductDTO;

import java.awt.*;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author 솔데스크
 */
public class Frame_GpuNext extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Cpu
     */
    public Frame_GpuNext(List<ProductDTO> gpulList) {
        this.gpuList = gpulList;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lbl_Gpu4 = new javax.swing.JLabel();
        Lbl_Gpu5 = new javax.swing.JLabel();
        Lbl_Gpu6 = new javax.swing.JLabel();
        Lbl_Name4 = new javax.swing.JLabel();
        Lbl_Name5 = new javax.swing.JLabel();
        Lbl_Name6 = new javax.swing.JLabel();
        Lbl_Price4 = new javax.swing.JLabel();
        Lbl_Price5 = new javax.swing.JLabel();
        Lbl_Price6 = new javax.swing.JLabel();
        Lbl_Info5 = new javax.swing.JLabel();
        Lbl_Info6 = new javax.swing.JLabel();
        Lbl_Info4 = new javax.swing.JLabel();
        Lbl_Exam4 = new javax.swing.JLabel();
        Lbl_Exam6 = new javax.swing.JLabel();
        Lbl_Exam5 = new javax.swing.JLabel();
        Button_Previous = new javax.swing.JButton();
        Btn_Selec4 = new javax.swing.JButton();
        Btn_Selec5 = new javax.swing.JButton();
        Btn_Selec6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel1.setText("GPU");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 3, 18)); // NOI18N
        // jLabel2.setText("아이템 추가는 소스에서 추가 가능");
        
        
        ImageIcon icon3 = new ImageIcon(getClass().getResource("/images/GPU/rx9070.jpg"));
        Image Image3 = icon3.getImage();
        Image resizeImage3 = Image3.getScaledInstance( 100, 80, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon3 = new ImageIcon(resizeImage3);
        Lbl_Gpu4.setIcon(resizedIcon3);
        Lbl_Gpu4.setText("");

        ImageIcon icon4 = new ImageIcon(getClass().getResource("/images/GPU/rtx4070.jpg"));
        Image Image4 = icon4.getImage();
        Image resizeImage4 = Image4.getScaledInstance( 100, 80, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon4 = new ImageIcon(resizeImage4);
        Lbl_Gpu5.setIcon(resizedIcon4);
        Lbl_Gpu5.setText("");

        ImageIcon icon5 = new ImageIcon(getClass().getResource("/images/GPU/a770.jpg"));
        Image Image5 = icon5.getImage();
        Image resizeImage5 = Image5.getScaledInstance( 100, 80, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon5 = new ImageIcon(resizeImage5);
        Lbl_Gpu6.setIcon(resizedIcon5);
        Lbl_Gpu6.setText(".");

        Lbl_Name4.setText("제조사:");

        Lbl_Name5.setText("제조사:");

        Lbl_Name6.setText("제조사:");

        Lbl_Price4.setText("제품명:");

        Lbl_Price5.setText("제품명:");

        Lbl_Price6.setText("제품명:");

        Lbl_Info5.setText("출시일:");

        Lbl_Info6.setText("출시일:");

        Lbl_Info4.setText("출시일:");

        Lbl_Exam4.setText("판매가:");

        Lbl_Exam6.setText("판매가:");

        Lbl_Exam5.setText("판매가:");

        setPreferredSize(new java.awt.Dimension(600, 550));

        Button_Previous.setText("이전 페이지");
        Button_Previous.setPreferredSize(new java.awt.Dimension(100, 30));
        Button_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PreviousActionPerformed(evt);
            }
        });

        Btn_Selec4.setText("추가");
        Btn_Selec5.setText("추가");        
        Btn_Selec6.setText("추가");
        
        
            
        ProductDAO productDAO = new ProductDAO();
        ProductDTO showProduct = gpuList.remove(0);
        jLabel4.setText(showProduct.getManufacturer());
        jLabel3.setText(showProduct.getProductName());
        jLabel5.setText(showProduct.getReleaseDate());
        jLabel8.setText(String.valueOf(showProduct.getPrice()));
        ProductDTO finalShowProduct4 = showProduct;
        Btn_Selec4.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, productDAO.addCart(finalShowProduct4.getProductId()) ? "카트에 제품 추가" : "카트에 해당 상품이 이미 담겨 있습니다");
        });
        
        showProduct = gpuList.remove(0);
        jLabel10.setText(showProduct.getManufacturer());
        jLabel11.setText(showProduct.getProductName());
        jLabel12.setText(showProduct.getReleaseDate());
        jLabel13.setText(String.valueOf(showProduct.getPrice()));
        ProductDTO finalShowProduct5 = showProduct;
        Btn_Selec5.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, productDAO.addCart(finalShowProduct5.getProductId()) ? "카트에 제품 추가" : "카트에 해당 상품이 이미 담겨 있습니다");
        });
        
        showProduct = gpuList.remove(0);
        jLabel14.setText(showProduct.getManufacturer());
        jLabel16.setText(showProduct.getProductName());
        jLabel18.setText(showProduct.getReleaseDate());
        jLabel19.setText(String.valueOf(showProduct.getPrice()));
        ProductDTO finalShowProduct6 = showProduct;
        Btn_Selec6.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, productDAO.addCart(finalShowProduct6.getProductId()) ? "카트에 제품 추가" : "카트에 해당 상품이 이미 담겨 있습니다");
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Gpu5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Name5)
                            .addComponent(Lbl_Info5)
                            .addComponent(Lbl_Exam5)
                            .addComponent(Lbl_Price5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Gpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Name4)
                            .addComponent(Lbl_Price4)
                            .addComponent(Lbl_Exam4)
                            .addComponent(Lbl_Info4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Gpu6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Price6)
                            .addComponent(Lbl_Name6)
                            .addComponent(Lbl_Exam6)
                            .addComponent(Lbl_Info6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Selec6)
                    .addComponent(Btn_Selec5)
                    .addComponent(Btn_Selec4))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Gpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Gpu5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Name5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Price5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Info5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Exam5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lbl_Gpu6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_Info6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Name6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Price6)
                                .addGap(26, 26, 26)
                                .addComponent(Lbl_Exam6))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Name4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Selec4)
                                .addGap(95, 95, 95)
                                .addComponent(Btn_Selec5)
                                .addGap(95, 95, 95)
                                .addComponent(Btn_Selec6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Price4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Info4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Exam4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PreviousActionPerformed
        // TODO add your handling code here:
        Frame_Gpu next = new Frame_Gpu();
        Point location = this.getLocation();
        next.setLocation(location);
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_PreviousActionPerformed

    private void Btn_Selec4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Selec4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Selec4ActionPerformed

    private void Btn_Selec5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Selec5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Selec5ActionPerformed

    private void Btn_Selec6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Selec6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Selec6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_GpuNext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_GpuNext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_GpuNext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_GpuNext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frame_GpuNext frame_gpuNext = new Frame_GpuNext(null);
                frame_gpuNext.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Selec4;
    private javax.swing.JButton Btn_Selec5;
    private javax.swing.JButton Btn_Selec6;
    private javax.swing.JButton Button_Previous;
    private javax.swing.JLabel Lbl_Exam4;
    private javax.swing.JLabel Lbl_Exam5;
    private javax.swing.JLabel Lbl_Exam6;
    private javax.swing.JLabel Lbl_Gpu4;
    private javax.swing.JLabel Lbl_Gpu5;
    private javax.swing.JLabel Lbl_Gpu6;
    private javax.swing.JLabel Lbl_Info4;
    private javax.swing.JLabel Lbl_Info5;
    private javax.swing.JLabel Lbl_Info6;
    private javax.swing.JLabel Lbl_Name4;
    private javax.swing.JLabel Lbl_Name5;
    private javax.swing.JLabel Lbl_Name6;
    private javax.swing.JLabel Lbl_Price4;
    private javax.swing.JLabel Lbl_Price5;
    private javax.swing.JLabel Lbl_Price6;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private List<ProductDTO> gpuList;
}
